<?php
$title = 'Add new product';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$product = $form->get('name');
$product->setAttribute('class', 'form-control');
$product->setAttribute('placeholder', 'Product name');

$brand = $form->get('brand');
$brand->setAttribute('class', 'form-control');
$brand->setAttribute('placeholder', 'Brand');

$ptype = $form->get('ptype');
$ptype->setAttribute('class', 'form-control');
$ptype->setAttribute('placeholder', 'Type');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('product', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($product) ?>
    <?= $this->formElement($product) ?>
    <?= $this->formElementErrors()->render($product, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($brand) ?>
    <?= $this->formElement($brand) ?>
    <?= $this->formElementErrors()->render($brand, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($ptype) ?>
    <?= $this->formElement($ptype) ?>
    <?= $this->formElementErrors()->render($brand, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();