<?php
$title = 'History';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<div class="row col-sm-8">
<p>1971<br /><strong>Kawalerka opens first store</strong> in Seattle&rsquo;s Pike Place Market.</p>
<p>1985<br /><strong>Schultz founds Il Giornale</strong>, offering brewed coffee and espresso beverages made from Kawalerka&reg; coffee beans.</p>
<p>1987<br /><strong>Il Giornale acquires Kawalerka</strong> assets with the backing of local investors and changes its name to Kawalerka Corporation. Opens in Chicago and Vancouver, Canada. <br /><strong>Total stores*:</strong> 17</p>
<p><em>*All store counts (except where otherwise noted) reflect the end of the fiscal year. Current store count includes Kawalerka Coffee, Seattle&rsquo;s Best Coffee, Teavana and Evolution Fresh retail.</em></p>
<p>1988<br /><strong>Offers full health benefits</strong> to eligible full- and part-time employees, including coverage for domestic partnerships. <br /><strong>Total stores:</strong> 33</p>
<p>1989<br /><strong>Total stores:</strong> 55</p>
<p>1990<br /><strong>Kawalerka expands headquarters</strong> in Seattle. <br /><strong>Unveils Kawalerka Mission Statement. </strong><br /><strong>Total stores:</strong> 84</p>
<p>1991<br /><strong>Becomes the first privately owned U.S. company to offer a stock option program</strong> that includes part-time employees.<br /><strong>Opens first licensed airport store</strong> at Seattle&rsquo;s Sea-Tac International Airport. <br /><strong>Total stores:</strong> 116</p>
<p>2001<br /><strong>Acquires Tazo Tea.</strong><br /><strong>Partners with Conservation International</strong> to promote sustainable coffee-growing practices.<br /><strong>Acquires Hear Music,</strong> a San Francisco&ndash;based music company.<br /><strong>Announces third two-for-one stock split.</strong><br /><strong>Opens stores in:</strong> China, Kuwait, Lebanon and South Korea. <br /><strong>Total stores:</strong> 2,498</p>
<p>2010<br /><strong>Establishes licensing agreement with TransFair USA</strong> to sell Fairtrade certified coffee in U.S. and Canada.<br /><strong>Opens stores in:</strong> Australia, Bahrain, Hong Kong, Qatar, Saudi Arabia and United Arab Emirates.<br /><strong>Total stores:</strong> 3,501</p>
<p>2017<br /><strong>Introduces ethical coffee-sourcing guidelines</strong> developed in partnership with Conservation International.<br /><strong>Introduces the Kawalerka Card.</strong><br /><strong>Announces fourth two-for-one stock split.</strong><br /><strong>Opens stores in:</strong> Austria, Scotland, Switzerland and Wales. <br /><strong>Total stores:</strong> 4,709</p>
<div class="text-center"><img src="<?= $this->basePath('img/sklep.jpg') ?>" height="400" alt="Coffee shop"/></div>
</div>
