<?php
$title = 'How to choose';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<div class="row col-sm-8">
<hr/>
<h2>Selecting the best tea</h2>
<p>With over 3000 varieties of tea, how do you choose teas that will appeal to you? We recommend referring to our flowchart or taking our Tea Interview below.</p>
<p><img src="https://cdn.shopify.com/s/files/1/0888/8900/files/Flowchart_1024x1024.png?17811879137373444375" alt="" /></p>
<p><strong>1. Are you looking for low, or no-caffeine beverages?</strong> If yes, view our <a href="https://www.teasource.com/collections/white-tea">White teas</a> or <a href="https://www.teasource.com/collections/herbal-teas">Herbal</a>. If no, go to the next question.</p>
<p><strong>2. Are you interested in real tea, or herbals?</strong> All real tea comes from the same plant, <em>camellia sinensis</em>, this includes: black tea, oolong tea, green tea, Earl Grey, English Breakfast, etc. Things like Peppermint or Chamomile come from different plants, not the tea plant, and thus actually contain no tea, and are commonly called herbal drinks.</p>
<p>If you are interested in herbals go to the <a href="https://www.teasource.com/collections/herbal-teas">Herbal</a> section.<br /> If you are interested in real tea go to the next question.</p>
<p><strong>3. Are you looking for a full-bodied tea?</strong> If yes, go to the <a href="https://www.teasource.com/collections/black-tea">Black</a> tea section. If no, go the next question.</p>
<p><strong>4. Are you looking for a light cup?</strong> If yes, visit <a href="https://www.teasource.com/collections/green-tea">Green teas</a> or <a href="https://www.teasource.com/collections/white-tea">White teas</a>. If no, go to the next question.</p>
<p><strong>5. Are you looking for an in-between cup (in terms of strength)?</strong> If yes, browse our <a href="https://www.teasource.com/collections/oolong-tea">Oolongs</a>.</p>
<p><strong>6. Are you looking for a straight tea (nothing but tea), or are you looking for a scented/flavored tea?</strong> i.e. tea that has had some other taste added (for example: Earl Grey, or black tea with mango, or jasmine, or green tea with lemon etc.)</p>
<p>If you are looking for a flavored tea, go to the appropriate tea category (Black, Green, or Oolong) and browse "Blends."<br /> If you are looking for a straight tea, check out teas in the appropriate category under Teas.
</p>
