<?php
$title = 'Add menu item';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<div class="row col-sm-8">
<hr/>
<?php
$menu = $form->get('name');
$menu->setAttribute('class', 'form-control');
$menu->setAttribute('placeholder', 'Name item');

$description = $form->get('description');
$description->setAttribute('class', 'form-control');
$description->setAttribute('placeholder', 'Description');

$price = $form->get('price');
$price->setAttribute('class', 'form-control');
$price->setAttribute('placeholder', 'Price');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('menu', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($menu) ?>
    <?= $this->formElement($menu) ?>
    <?= $this->formElementErrors()->render($menu, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($description) ?>
    <?= $this->formElement($description) ?>
    <?= $this->formElementErrors()->render($description, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($price) ?>
    <?= $this->formElement($price) ?>
    <?= $this->formElementErrors()->render($price, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>
</div>
