<?php
// module/Menu/view/menu/menu/delete.phtml:

$title = 'Usuwanie menu';
$url   = $this->url('menu', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<div class="row col-sm-8">
<hr/>
<p>
    Czy na pewno chcesz usunąć item
    "<?= $this->escapeHtml($menu->name) ?>" ?
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $menu->id ?>" />
    <input type="submit" class="btn-lg btn-danger" name="del" value="Yes" />
    <input type="submit" class="btn-lg btn-success" name="del" value="No" />
</div>
</form>
</div>
