<?php
$title = 'Menu';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<hr/ class="row col-sm-8">
<table class="table">
<tr class="active">
    <th>Name</th>
    <th>Description</th>
    <th class="text-center">Price</th>
    <th></th>

</tr>
<?php foreach ($menus as $menu) : ?>
    <tr>
        <td><?= $this->escapeHtml($menu->name) ?></td>
        <td><?= $this->escapeHtml($menu->description) ?></td>
        <td class="text-center">$<?= $this->escapeHtml($menu->price) ?></td>
        <td class="text-center">
            <a href="<?= $this->url('menu', ['action' => 'edit', 'id' => $menu->id]) ?>" class ="btn-sm btn-primary">
                Edit
            </a>
            <a href="<?= $this->url('menu', ['action' => 'delete', 'id' => $menu->id]) ?>" class ="btn-sm btn-danger">
                Delete
            </a>
        </td>
    </tr>
<?php endforeach; ?>
</table>
<p class="text-right">
    <a href="<?= $this->url('menu', ['action' => 'add']) ?>" class ="btn-sm btn-info">
        Add new item
    </a>
</p>
