<h1><span class="text-info">Kawalerka</span> - coffee, tea, cake</h1>
<div class="row col-sm-8">
<hr/>
<p>Intimate interior in the heart of old Krakow. Cafe Bar Kawalerka is located in the Historical Museum of Krakow; Hippolytes House on the Mariacki Square, a few meters from the Market Square. If you are looking for a place in the center, away from the hustle and bustle, Cafe Bar Kawalerka is just for you. Here you can enjoy delicious coffee, which we offer daily fresh pastries. Fast lunch and a glass of wine? No problem. Our card is frequently updated so you will not get bored of our menu.</p>
<p>Ideal for evening chats with a glass of wine or sophisticated cocktail, with calm background music and intimate atmosphere. A beautiful historical garden in which flowers bloom will be for you, certainly a relaxing moment in warm weather.</p>
<h2>Kawalerka</h2>
<p>Mariacki Square 3<br /> 31-042 Krak&oacute;w<br /> tel. 12 426 47 73<br /><a title="kontakt@cafekawalerka.pl" href="mailto:kontakt@cafekawalerka.pl">kontakt@cafekawalerka.pl</a></p>
  <br>
  <img src="<?= $this->basePath('img/stock.jpg') ?>" height="400" alt="Coffee shop"/>
</div>
